// <auto-generated/>
namespace App.File.CrystalReport.Desktop
{
    partial class ReportForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.ReportViewer = new CrystalDecisions.Windows.Forms.CrystalReportViewer();
            this.LoaderPicture = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.LoaderPicture)).BeginInit();
            this.SuspendLayout();
            // 
            // ReportViewer
            // 
            this.ReportViewer.ActiveViewIndex = -1;
            this.ReportViewer.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.ReportViewer.Cursor = System.Windows.Forms.Cursors.Default;
            this.ReportViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ReportViewer.Location = new System.Drawing.Point(0, 0);
            this.ReportViewer.Name = "ReportViewer";
            this.ReportViewer.ReuseParameterValuesOnRefresh = true;
            this.ReportViewer.ShowGroupTreeButton = false;
            this.ReportViewer.ShowLogo = false;
            this.ReportViewer.ShowParameterPanelButton = false;
            this.ReportViewer.ShowRefreshButton = false;
            this.ReportViewer.Size = new System.Drawing.Size(1024, 502);
            this.ReportViewer.TabIndex = 0;
            this.ReportViewer.ToolPanelWidth = 150;
            // 
            // LoaderPicture
            // 
            this.LoaderPicture.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.LoaderPicture.Image = global::App.File.CrystalReport.Properties.Resources.LoaderPicture;
            this.LoaderPicture.Location = new System.Drawing.Point(490, 190);
            this.LoaderPicture.Name = "LoaderPicture";
            this.LoaderPicture.Size = new System.Drawing.Size(48, 48);
            this.LoaderPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.LoaderPicture.TabIndex = 1;
            this.LoaderPicture.TabStop = false;
            // 
            // ReportForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(1024, 502);
            this.Controls.Add(this.LoaderPicture);
            this.Controls.Add(this.ReportViewer);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "ReportForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Visualizar Relatório";
            ((System.ComponentModel.ISupportInitialize)(this.LoaderPicture)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal CrystalDecisions.Windows.Forms.CrystalReportViewer ReportViewer;
        internal System.Windows.Forms.PictureBox LoaderPicture;
    }
}