//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Cohab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Cohab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  Sistema_Sigla 
        ///	, Sistema_Nome 
        ///	FROM 
        ///		Sistema AS si
        ///	ORDER BY 
        ///		Sistema_Sigla ASC;
        ///--.
        /// </summary>
        internal static string sql_SistemaListar {
            get {
                return ResourceManager.GetString("sql_SistemaListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  Sistema_Sigla 
        ///	, Sistema_Nome 
        ///	FROM 
        ///		Sistema AS si
        ///		LEFT JOIN UsuarioSistema AS us 
        ///			ON si.Sistema_Sigla = us.UsuarioSistema_SistemaSigla
        ///	WHERE 
        ///		us.UsuarioSistema_UsuarioLogin = @Login
        ///	ORDER BY 
        ///		Sistema_Sigla ASC;
        ///--.
        /// </summary>
        internal static string sql_SistemaListarPorUsuario {
            get {
                return ResourceManager.GetString("sql_SistemaListarPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  Sistema_Sigla 
        ///	, Sistema_Nome 
        ///	FROM 
        ///		Sistema AS si
        ///	WHERE 
        ///		(Sistema_Proprio = @proprio OR (@proprio = 0 OR @proprio IS NULL))
        ///	ORDER BY 
        ///		Sistema_Sigla ASC;
        ///--.
        /// </summary>
        internal static string sql_SistemaListarProprio {
            get {
                return ResourceManager.GetString("sql_SistemaListarProprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE FROM [DB_COHAB].[dbo].[UsuarioSistema] 
        ///WHERE 1 = 1 
        ///	AND [UsuarioSistema_UsuarioLogin] = @loginDestino;
        ///
        ///INSERT INTO [DB_COHAB].[dbo].[UsuarioSistema] 
        ///    ( 
        ///	 [UsuarioSistema_Senha] 
        ///    ,[UsuarioSistema_Ativo] 
        ///    ,[UsuarioSistema_Validade] 
        ///    ,[UsuarioSistema_Free] 
        ///    ,[UsuarioSistema_UsuarioLogin] 
        ///    ,[UsuarioSistema_GrupoId] 
        ///    ,[UsuarioSistema_SistemaSigla] 
        ///    ,[UsuarioSistema_Micro] 
        ///    ,[UsuarioSistema_UsuarioRede] 
        ///    ,[UsuarioSistema_Data] 
        ///    ,[UsuarioSi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sql_UsuarioClonarAcessos {
            get {
                return ResourceManager.GetString("sql_UsuarioClonarAcessos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  Usuario_Login 
        ///	, Usuario_Nome 
        ///	, Usuario_Matricula 
        ///	, Usuario_Ramal 
        ///	, Usuario_Email 
        ///	, Usuario_Chefia 
        ///	, Usuario_Ativo 
        ///	, Usuario_Visivel 
        ///	, Usuario_Notes 
        ///FROM Usuario AS us WITH (NOLOCK) 
        ///WHERE 1 = 1 
        ///	AND (Usuario_Ativo = @Ativo 
        ///		OR (@Ativo = 0 OR @Ativo IS NULL))
        ///	AND (Usuario_Login = @Login 
        ///		OR (@Login = &apos;&apos; OR @Login IS NULL))
        ///	AND (Usuario_Nome LIKE &apos;%&apos;+@Nome+&apos;%&apos; 
        ///		OR (@Nome = &apos;&apos; OR @Nome IS NULL))
        ///ORDER BY 
        ///	Usuario_Nome ASC;
        ///--.
        /// </summary>
        internal static string sql_UsuarioListar {
            get {
                return ResourceManager.GetString("sql_UsuarioListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  U.Usuario_Matricula 
        ///	, U.Usuario_Nome 
        ///	, U.Usuario_Login 
        ///	, U.Usuario_Email 
        ///	, U.Usuario_Notes 
        ///FROM [vw_lotacaodp] L WITH (nolock) 
        ///	INNER JOIN Usuario U WITH (nolock) ON U.Usuario_Login = L.Usuario_Login 
        ///WHERE 1 = 1 
        ///	AND (COALESCE(@depto, &apos;&apos;) = &apos;&apos; OR L.[departamento_sigla] = @depto) 
        ///	AND (COALESCE(@exclusivo, 0) = 0 OR L.[setor_sigla] IS NULL) 
        ///	AND (COALESCE(@ativos, 0) = 0 OR U.usuario_ativo = @ativos)
        ///ORDER BY U.[Usuario_Nome] ASC;
        ///--.
        /// </summary>
        internal static string sql_UsuarioListarPorDepartamento {
            get {
                return ResourceManager.GetString("sql_UsuarioListarPorDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  U.Usuario_Login 
        ///	, U.Usuario_Nome 
        ///	, U.Usuario_Matricula 
        ///	, U.Usuario_Ramal 
        ///	, U.Usuario_Email 
        ///	, U.Usuario_Chefia 
        ///	, U.Usuario_Ativo 
        ///	, U.Usuario_Visivel 
        ///	, U.Usuario_Notes 
        ///FROM [vw_lotacaodp] L WITH (nolock) 
        ///	INNER JOIN Usuario U WITH (nolock) ON U.Usuario_Login = L.Usuario_Login 
        ///WHERE 1 = 1 
        ///	AND (COALESCE(@matricula, &apos;&apos;) = &apos;&apos; OR L.[matricula] = @matricula) 
        ///	AND (COALESCE(@login, &apos;&apos;) = &apos;&apos; OR U.[usuario_login] = @login) 
        ///ORDER BY U.[Usuario_Nome] ASC;
        ///--.
        /// </summary>
        internal static string sql_UsuarioListarPorMatricula {
            get {
                return ResourceManager.GetString("sql_UsuarioListarPorMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  U.Usuario_Matricula 
        ///	, U.Usuario_Nome 
        ///	, U.Usuario_Login 
        ///	, U.Usuario_Email 
        ///	, U.Usuario_Notes 
        ///FROM [vw_lotacaodp] L WITH (nolock) 
        ///	INNER JOIN Usuario U WITH (nolock) ON U.Usuario_Login = L.Usuario_Login 
        ///WHERE 1 = 1 
        ///	AND (COALESCE(@setor, &apos;&apos;) = &apos;&apos; OR l.setor_sigla = @setor OR l.Departamento_Sigla = @setor) 
        ///	AND (U.Usuario_Ativo = @ativos) 
        ///ORDER BY u.Usuario_Nome ASC;
        ///--.
        /// </summary>
        internal static string sql_UsuarioListarPorSetor {
            get {
                return ResourceManager.GetString("sql_UsuarioListarPorSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///UPDATE 
        ///	UsuarioSistema 
        ///	SET 
        ///		  UsuarioSistema_Senha = @Senha 
        ///		, UsuarioSistema_Validade = @Validade 
        ///	WHERE 
        ///		UsuarioSistema_UsuarioLogin = @Login 
        ///		AND UsuarioSistema_SistemaSigla = @Sistema;
        ///--.
        /// </summary>
        internal static string sql_UsuarioTrocarSenha {
            get {
                return ResourceManager.GetString("sql_UsuarioTrocarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	Usuario_Login
        ///	FROM 
        ///		Usuario AS us
        ///		LEFT JOIN UsuarioSistema AS usi 
        ///			ON us.Usuario_Login = usi.UsuarioSistema_UsuarioLogin
        ///	WHERE 
        ///		us.Usuario_Login = @Login
        ///		AND usi.UsuarioSistema_SistemaSigla = @Sistema
        ///	ORDER BY 
        ///		Usuario_Login ASC;
        ///--.
        /// </summary>
        internal static string sql_UsuarioVerificarAcesso {
            get {
                return ResourceManager.GetString("sql_UsuarioVerificarAcesso", resourceCulture);
            }
        }
    }
}
