// <auto-generated/>
namespace App.Core.Desktop
{
    partial class FlatMaskedTextBox
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.MainTextBox = new FlatMaskedTextBoxBase();
            this.PlaceholderLabel = new System.Windows.Forms.Label();
            this.pnlText = new System.Windows.Forms.Panel();
            this.ActionButton = new App.Core.Desktop.FlatButton();
            this.ContentPanel.SuspendLayout();
            this.pnlText.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlContent
            // 
            this.ContentPanel.Controls.Add(this.pnlText);
            this.ContentPanel.Controls.Add(this.ActionButton);
            this.ContentPanel.Padding = new System.Windows.Forms.Padding(1, 2, 2, 2);
            this.ContentPanel.Controls.SetChildIndex(this.ActionButton, 0);
            this.ContentPanel.Controls.SetChildIndex(this.SubtitleLabel, 0);
            this.ContentPanel.Controls.SetChildIndex(this.pnlText, 0);
            // 
            // txtMain
            // 
            this.MainTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.MainTextBox.BackColor = System.Drawing.Color.White;
            this.MainTextBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.MainTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(47)))), ((int)(((byte)(47)))));
            this.MainTextBox.Location = new System.Drawing.Point(8, 0);
            this.MainTextBox.Margin = new System.Windows.Forms.Padding(0);
            this.MainTextBox.Name = "txtMain";
            this.MainTextBox.Size = new System.Drawing.Size(186, 16);
            this.MainTextBox.TabIndex = 0;
            // 
            // lblPlaceholder
            // 
            this.PlaceholderLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PlaceholderLabel.BackColor = System.Drawing.Color.Transparent;
            this.PlaceholderLabel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.PlaceholderLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.PlaceholderLabel.Location = new System.Drawing.Point(5, -1);
            this.PlaceholderLabel.Margin = new System.Windows.Forms.Padding(0);
            this.PlaceholderLabel.Name = "lblPlaceholder";
            this.PlaceholderLabel.Size = new System.Drawing.Size(189, 15);
            this.PlaceholderLabel.TabIndex = 0;
            // 
            // pnlText
            // 
            this.pnlText.BackColor = System.Drawing.Color.Transparent;
            this.pnlText.Controls.Add(this.PlaceholderLabel);
            this.pnlText.Controls.Add(this.MainTextBox);
            this.pnlText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlText.Location = new System.Drawing.Point(1, 15);
            this.pnlText.Name = "pnlText";
            this.pnlText.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.pnlText.Size = new System.Drawing.Size(177, 15);
            this.pnlText.TabIndex = 0;
            // 
            // btnAction
            // 
            this.ActionButton.BackgroundImage = global::App.Core.Properties.Resources.img_calendar_dark;
            this.ActionButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.ActionButton.Dock = System.Windows.Forms.DockStyle.Right;
            this.ActionButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ActionButton.FlatAppearance.BorderSize = 0;
            this.ActionButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ActionButton.Location = new System.Drawing.Point(178, 2);
            this.ActionButton.MaximumSize = new System.Drawing.Size(24, 0);
            this.ActionButton.Name = "btnAction";
            this.ActionButton.Size = new System.Drawing.Size(24, 28);
            this.ActionButton.TabIndex = 1;
            this.ActionButton.TabStop = false;
            this.ActionButton.Visible = false;
            // 
            // FlatMaskedTextBox
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Name = "FlatMaskedTextBox";
            this.ContentPanel.ResumeLayout(false);
            this.ContentPanel.PerformLayout();
            this.pnlText.ResumeLayout(false);
            this.pnlText.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        protected FlatMaskedTextBoxBase MainTextBox;
        protected System.Windows.Forms.Label PlaceholderLabel;
        private System.Windows.Forms.Panel pnlText;
        private FlatButton ActionButton;

    }
}
