// <auto-generated/>
namespace App.Core.Desktop
{
    partial class MainBaseForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.HeadPanel = new App.Core.Desktop.FlatPanelBG();
            this.BodyPanel = new App.Core.Desktop.FlatPanelBG();
            this.ContentPanel = new App.Core.Desktop.FlatPanel();
            this.FootPanel = new App.Core.Desktop.FlatPanelBG();
            this.MainStatusBar = new App.Core.Desktop.FlatStatusBar();
            this.HeadPanel.SuspendLayout();
            this.BodyPanel.SuspendLayout();
            this.FootPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // HeadPanel
            // 
            this.HeadPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.HeadPanel.BackColorType = App.Core.Desktop.PanelType.control;
            this.HeadPanel.Controls.Add(this.BodyPanel);
            this.HeadPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HeadPanel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.HeadPanel.Location = new System.Drawing.Point(0, 0);
            this.HeadPanel.Margin = new System.Windows.Forms.Padding(0);
            this.HeadPanel.Name = "HeadPanel";
            this.HeadPanel.Padding = new System.Windows.Forms.Padding(8);
            this.HeadPanel.Size = new System.Drawing.Size(480, 246);
            // 
            // BodyPanel
            // 
            this.BodyPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.BodyPanel.BackColorType = App.Core.Desktop.PanelType.white;
            this.BodyPanel.BorderRound = true;
            this.BodyPanel.BorderSize = 1;
            this.BodyPanel.Controls.Add(this.ContentPanel);
            this.BodyPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BodyPanel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.BodyPanel.Location = new System.Drawing.Point(8, 8);
            this.BodyPanel.Margin = new System.Windows.Forms.Padding(0);
            this.BodyPanel.Name = "BodyPanel";
            this.BodyPanel.Padding = new System.Windows.Forms.Padding(5);
            this.BodyPanel.Size = new System.Drawing.Size(464, 230);
            // 
            // ContentPanel
            // 
            this.ContentPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ContentPanel.Location = new System.Drawing.Point(5, 5);
            this.ContentPanel.Name = "ContentPanel";
            this.ContentPanel.Size = new System.Drawing.Size(454, 220);
            // 
            // FootPanel
            // 
            this.FootPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.FootPanel.BackColorType = App.Core.Desktop.PanelType.control;
            this.FootPanel.Controls.Add(this.MainStatusBar);
            this.FootPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.FootPanel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.FootPanel.Location = new System.Drawing.Point(0, 246);
            this.FootPanel.Margin = new System.Windows.Forms.Padding(0);
            this.FootPanel.Name = "FootPanel";
            this.FootPanel.Size = new System.Drawing.Size(480, 24);
            this.FootPanel.TabIndex = 1;
            // 
            // MainStatusBar
            // 
            this.MainStatusBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(145)))), ((int)(((byte)(145)))));
            this.MainStatusBar.BackColorContent = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.MainStatusBar.BorderEnable = false;
            this.MainStatusBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainStatusBar.Location = new System.Drawing.Point(0, 0);
            this.MainStatusBar.Movimento = App.Core.Desktop.Movimento.Nenhum;
            this.MainStatusBar.Name = "MainStatusBar";
            this.MainStatusBar.Registros = 0;
            this.MainStatusBar.Size = new System.Drawing.Size(480, 24);
            this.MainStatusBar.TabIndex = 0;
            // 
            // MainBaseForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(480, 270);
            this.Controls.Add(this.HeadPanel);
            this.Controls.Add(this.FootPanel);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MinimumSize = new System.Drawing.Size(200, 200);
            this.Name = "MainBaseForm";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainBaseForm";
            this.HeadPanel.ResumeLayout(false);
            this.BodyPanel.ResumeLayout(false);
            this.FootPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private FlatPanelBG FootPanel;
        private FlatPanelBG HeadPanel;
        private FlatPanelBG BodyPanel;
        protected FlatPanel ContentPanel;
        public FlatStatusBar MainStatusBar;

    }
}